# Site settings
title: A Junior Developer portfolio
description: Sheila Zhao
# baseurl: "/particle" # the subpath of your site, e.g. /blog
#url: "https://heinerom.github.io/#" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sheila Zhao
user_description: Self-motivated, solutions-oriented junior software developer with project experience and academic training in developing software and web applications.
user_title: Software Developer
email: sheilazhao64@gmail.com
github_username:  heinerom

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
