# Site settings
title: Portfolio of Sheila.Z
description: Sheila Zhao
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://heinerom.github.io/#" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sheila Zhao
user_description: A junior software developer who loves challanges! I have a Bsc of Engineering at University of Calgary and just finished Oriented-objected Software Development(OOSD) program at SAIT. I am equipped with a diverse set of skills, ranging from PHP + HTML + CSS + Js, to .NET/ASP, and database as SQL, Oracle and Azura. 
user_title: Software Developer
email: sheilazhao64@gmail.com
github_username:  heinerom

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
